import { analyzeCallCopy, resolveCallCopy, type CallCopyKind, type CallCopyPolicy } from "./callsign-copy.js";
import { parseContestTransmission, type OperatorIntent } from "./cw-contest-parser.js";

export type CallMatch = CallCopyKind;
export type QsoCheck = "OK" | "CALL" | "RST" | "NR" | "NIL" | "DUP";
export type SpLogicalState = "waiting-for-tune" | "calling-cq" | "busy-with-other-station" | "need-operator-call" | "need-operator-number" | "need-operator-call-and-number" | "ready-to-acknowledge" | "closing" | "cooldown" | "completed" | "failed" | "aborted";
export type SpPhysicalState = "listening" | "copying" | "preparing" | "sending";
export type SpQsoPhase = "idle" | "listening-cq" | "station-busy" | "calling-station" | "awaiting-reply" | "receiving-exchange" | "sending-our-exchange" | "station-requesting-call" | "station-requesting-number" | "station-requesting-again" | "awaiting-tu" | "completed" | "failed" | "aborted";
export type SpIncident = "busy" | "ignore-first-call" | "request-agn" | "request-call" | "request-number" | "repeat-exchange" | "partial-operator-call" | "b4" | "nil" | "qrl" | "qsy" | "wrong-number-correction";
export type SpStationMessage = "busy" | "exchange" | "agn" | "call" | "number" | "final" | "tu" | "b4" | "nil" | "qrl" | "qsy";
export interface SpStationProfile { style: "precise" | "impatient" | "lid"; replyTimeoutMs: number; acknowledgement: "tu" | "r-number-tu" | "rr-tu"; repeatsExchangeOnTimeout: boolean; }

export interface SpQsoScenario { id: string; stationCall: string; spottedCallsign: string; operatorCall: string; exchange: string; rst: string; wpm: number; toneOffsetHz: number; signalLevel: number; skill: 1 | 2 | 3; patience: number; responseDelayMs: number; profile: SpStationProfile; initialBehavior: "normal" | "busy" | "ignores-first-call"; operatorCallCopy: CallMatch; operatorExchangeCopy: CallMatch; callCopyPolicy: CallCopyPolicy; repeatCount: 1 | 2; incidents: readonly SpIncident[]; }
export interface SpQsoState { phase: SpQsoPhase; logical: SpLogicalState; physical: SpPhysicalState; scenario?: SpQsoScenario; serial: string; patience: number; callAttempts: number; usedIncidents: readonly SpIncident[]; pendingOperator?: "initial-call" | "requested-call" | "requested-again" | "our-exchange" | "requested-number" | "agn-request" | "number-request" | "call-request"; returnPhase?: SpQsoPhase; returnLogical?: SpLogicalState; lastOperatorText?: string; transmittedOperatorCall?: string; heardOperatorCall?: string; copyChallengeUsed: boolean; lastStationText?: string; registered: boolean; }
export type SpQsoEffect = { type: "play-operator"; text: string } | { type: "play-station"; text: string; message: SpStationMessage; delayMs?: number } | { type: "start-reply-timeout"; delayMs: number } | { type: "cancel-reply-timeout" } | { type: "status"; label: string } | { type: "register-qso"; result: QsoCheck } | { type: "record-error" } | { type: "mark-worked" } | { type: "restart-cq" } | { type: "clear-entry" } | { type: "update-spot-status"; status: "BUSY" | "WORKED" | "FAILED" };
export type SpQsoEvent = { type: "start"; scenario: SpQsoScenario; serial: string } | { type: "operator-transmitted"; text: string; intent?: OperatorIntent } | { type: "operator-call"; text?: string } | { type: "operator-exchange"; call: string; rst: string; exchange: string } | { type: "operator-send-exchange" } | { type: "operator-tu" } | { type: "operator-agn" } | { type: "operator-number-request" } | { type: "operator-call-request" } | { type: "operator-repeat" } | { type: "operator-finished" } | { type: "station-finished"; message: SpStationMessage } | { type: "reply-timeout" } | { type: "tuned-out" } | { type: "abort" };
export interface SpQsoTransition { state: SpQsoState; effects: readonly SpQsoEffect[]; }
export const INITIAL_SP_QSO_STATE: SpQsoState = { phase: "idle", logical: "waiting-for-tune", physical: "listening", serial: "001", patience: 0, callAttempts: 0, usedIncidents: [], copyChallengeUsed: false, registered: false };

const normalize = (value: string): string => value.trim().toUpperCase().replace(/[^A-Z0-9/?]/g, "");
export function compareCallsign(entered: string, expected: string): CallMatch { return analyzeCallCopy(expected, entered).kind; }
export function checkSpQso(entry: { call: string; rst: string; exchange: string }, scenario: SpQsoScenario, duplicate = false): QsoCheck { if (duplicate) return "DUP"; const call = compareCallsign(entry.call, scenario.stationCall); if (call !== "exact") return call === "almost" ? "CALL" : "NIL"; if (normalize(entry.rst) !== scenario.rst) return "RST"; return normalize(entry.exchange) === scenario.exchange ? "OK" : "NR"; }
const has = (state: SpQsoState, item: SpIncident): boolean => state.scenario?.incidents.includes(item) === true && !state.usedIncidents.includes(item);
const consume = (state: SpQsoState, item: SpIncident): SpQsoState => ({ ...state, usedIncidents: state.usedIncidents.includes(item) ? state.usedIncidents : [...state.usedIncidents, item] });
const station = (state: SpQsoState, text: string, message: SpStationMessage, phase: SpQsoPhase, logical: SpLogicalState, delayed = false): SpQsoTransition => ({ state: { ...state, phase, logical: delayed ? state.returnLogical ?? logical : logical, physical: "sending", lastStationText: text }, effects: [{ type: "play-station", text, message, ...(delayed ? { delayMs: state.scenario?.responseDelayMs } : {}) }] });
const withTimeoutCancel = (transition: SpQsoTransition): SpQsoTransition => ({ ...transition, effects: [{ type: "cancel-reply-timeout" }, ...transition.effects] });
const startReplyTimeout = (state: SpQsoState): SpQsoEffect => ({ type: "start-reply-timeout", delayMs: state.scenario!.profile.replyTimeoutMs });
const finalAcknowledgement = (state: SpQsoState, scenario: SpQsoScenario): string => scenario.profile.acknowledgement === "r-number-tu" ? `R ${state.serial} TU` : scenario.profile.acknowledgement === "rr-tu" ? "RR TU" : "TU";
const stationExchange = (state: SpQsoState, scenario: SpQsoScenario): string => {
  if (!has(state, "wrong-number-correction")) return `${scenario.operatorCall} 5NN ${scenario.exchange}`;
  const wrong = String(Number(scenario.exchange) + 1).padStart(scenario.exchange.length, "0");
  return `${scenario.operatorCall} 5NN ${wrong} EEEEE ${scenario.exchange}`;
};
const endWithoutQso = (state: SpQsoState, status: "FAILED" | "WORKED" = "FAILED"): SpQsoTransition => ({ state: { ...state, phase: "failed", logical: "failed", physical: "listening" }, effects: [{ type: "cancel-reply-timeout" }, { type: "status", label: status === "WORKED" ? "QSO B4" : "QSO ENCERRADO" }, { type: "update-spot-status", status }, { type: "restart-cq" }] });
const op = (state: SpQsoState, text: string, pending: NonNullable<SpQsoState["pendingOperator"]>, label: string, phase: SpQsoPhase = "calling-station", returnPhase?: SpQsoPhase, returnLogical?: SpLogicalState): SpQsoTransition => ({ state: { ...state, phase, logical: phase === "sending-our-exchange" ? "need-operator-number" : "need-operator-call", physical: "sending", pendingOperator: pending, returnPhase, returnLogical, lastOperatorText: text }, effects: [{ type: "cancel-reply-timeout" }, { type: "play-operator", text }, { type: "status", label }] });
const partialCallCopy = (call: string): string => {
  if (call.length >= 4) return `${call.slice(0, -2)}?${call.slice(-1)}`;
  return `${call.slice(0, -1)}?`;
};

const failCallCopy = (state: SpQsoState): SpQsoTransition => ({ state: { ...state, phase: "failed", logical: "failed", physical: "listening" }, effects: [{ type: "cancel-reply-timeout" }, { type: "status", label: "FAILED" }, { type: "update-spot-status", status: "FAILED" }, { type: "restart-cq" }] });

/** Decide a resposta da estação a toda transmissão do indicativo do operador. */
const respondToOperatorCall = (state: SpQsoState, scenario: SpQsoScenario): SpQsoTransition => {
  if (has(state, "b4")) return station(consume(state, "b4"), "QSO B4", "b4", "awaiting-tu", "closing", true);
  if (has(state, "qrl")) return station(consume(state, "qrl"), "QRL", "qrl", "awaiting-tu", "closing", true);
  if (has(state, "qsy")) return station(consume(state, "qsy"), "QSY", "qsy", "awaiting-tu", "closing", true);
  if (has(state, "busy")) return station(consume(state, "busy"), "W1AW 5NN 047 TU", "busy", "station-busy", "busy-with-other-station");
  if (has(state, "ignore-first-call")) return { state: { ...consume(state, "ignore-first-call"), phase: "listening-cq", logical: "calling-cq", physical: "listening" }, effects: [{ type: "status", label: "SEM RESPOSTA" }, { type: "restart-cq" }] };
  const policy = scenario.callCopyPolicy ?? { model: "legacy" as const, skill: scenario.skill, acceptAlmost: false, rejectExact: false };
  const transmittedOperatorCall = state.transmittedOperatorCall ?? state.lastOperatorText ?? scenario.operatorCall;
  const partialIncident = has(state, "partial-operator-call");
  const heardOperatorCall = partialIncident ? partialCallCopy(transmittedOperatorCall) : transmittedOperatorCall;
  const heardState = partialIncident ? consume({ ...state, transmittedOperatorCall, heardOperatorCall }, "partial-operator-call") : { ...state, transmittedOperatorCall, heardOperatorCall };
  const copy = resolveCallCopy(scenario.operatorCall, heardOperatorCall, policy);
  const tolerateAlmost = policy.acceptAlmost || policy.skill === 1;
  if (has(heardState, "request-call")) return station(consume(heardState, "request-call"), "CALL?", "call", "station-requesting-call", "need-operator-call", true);
  if (has(heardState, "request-agn")) return station(consume(heardState, "request-agn"), "AGN?", "agn", "station-requesting-again", "need-operator-call", true);
  const forceRepeat = copy.kind === "exact" && policy.rejectExact && !heardState.copyChallengeUsed;
  if (forceRepeat) return station({ ...heardState, copyChallengeUsed: true }, "CALL?", "call", "station-requesting-call", "need-operator-call", true);
  if (copy.kind === "wrong" && has(heardState, "nil")) return station(consume(heardState, "nil"), "NIL", "nil", "station-requesting-call", "need-operator-call", true);
  if (copy.kind === "wrong" || (copy.kind === "almost" && !tolerateAlmost)) {
    const retry = { ...heardState, patience: heardState.patience - 1 };
    return retry.patience > 0 ? station(retry, "CALL?", "call", "station-requesting-call", "need-operator-call", true) : failCallCopy(retry);
  }
  return station(heardState, stationExchange(heardState, scenario), "exchange", "awaiting-reply", "need-operator-call-and-number", true);
};

export function createSpQsoScenario(stationCall: string, operatorCall: string, exchange: string, random: () => number, details: Partial<Pick<SpQsoScenario, "id" | "wpm" | "toneOffsetHz" | "signalLevel" | "skill" | "patience" | "responseDelayMs" | "profile">> = {}): SpQsoScenario { const choices: SpIncident[] = ["busy", "ignore-first-call", "request-agn", "request-call", "request-number", "repeat-exchange", "partial-operator-call", "b4", "nil", "qrl", "qsy", "wrong-number-correction"]; const roll = random(); const count = roll < .12 ? 2 : roll < .4 ? 1 : 0; const incidents: SpIncident[] = []; while (incidents.length < count) { const item = choices[Math.floor(random() * choices.length)]!; if (!incidents.includes(item)) incidents.push(item); } const profileRoll = random(); const profile = details.profile ?? (profileRoll < .55 ? { style: "precise" as const, replyTimeoutMs: 8000, acknowledgement: "tu" as const, repeatsExchangeOnTimeout: false } : profileRoll < .8 ? { style: "impatient" as const, replyTimeoutMs: 3000, acknowledgement: "rr-tu" as const, repeatsExchangeOnTimeout: false } : { style: "lid" as const, replyTimeoutMs: 5000, acknowledgement: "r-number-tu" as const, repeatsExchangeOnTimeout: true }); const defaults = profile.style === "precise" ? { skill: 3 as const, patience: 6, wpm: 34, responseDelayMs: 160 } : profile.style === "impatient" ? { skill: 3 as const, patience: 2, wpm: 30, responseDelayMs: 180 } : { skill: 1 as const, patience: 4, wpm: 24, responseDelayMs: 320 }; const skill = details.skill ?? defaults.skill; return { id: details.id ?? normalize(stationCall), stationCall: normalize(stationCall), spottedCallsign: normalize(stationCall), operatorCall: normalize(operatorCall), exchange: normalize(exchange).padStart(3, "0"), rst: "599", wpm: details.wpm ?? defaults.wpm, toneOffsetHz: details.toneOffsetHz ?? 0, signalLevel: details.signalLevel ?? 0, skill, patience: details.patience ?? defaults.patience, responseDelayMs: details.responseDelayMs ?? defaults.responseDelayMs, profile, initialBehavior: incidents.includes("busy") ? "busy" : incidents.includes("ignore-first-call") ? "ignores-first-call" : "normal", operatorCallCopy: incidents.includes("partial-operator-call") ? "almost" : "exact", operatorExchangeCopy: incidents.includes("repeat-exchange") ? "almost" : "exact", callCopyPolicy: { model: "morse", skill, acceptAlmost: profile.style === "lid", rejectExact: profile.style === "lid" }, repeatCount: 1, incidents }; }

export function reduceSpQso(state: SpQsoState, event: SpQsoEvent): SpQsoTransition {
  if (event.type === "abort" || event.type === "tuned-out") return { state: { ...state, phase: "aborted", logical: "aborted", physical: "listening", pendingOperator: undefined }, effects: [{ type: "status", label: "QSO ABORTADO" }, { type: "clear-entry" }] };
  if (event.type === "start") return { state: { phase: "listening-cq", logical: "calling-cq", physical: "listening", scenario: event.scenario, serial: event.serial, patience: event.scenario.patience, callAttempts: 0, usedIncidents: [], copyChallengeUsed: false, registered: false }, effects: [{ type: "status", label: "CQ" }, { type: "clear-entry" }] };
  const s = state.scenario; if (!s || ["idle", "completed", "failed", "aborted"].includes(state.phase)) return { state, effects: [] };
  if (event.type === "operator-transmitted") { const intent = event.intent ?? parseContestTransmission(event.text, { operatorCall: s.operatorCall, stationCall: s.stationCall, operatorSerial: state.serial, stationExchange: s.exchange }); if (intent.kind === "call-station") return reduceSpQso(state, { type: "operator-call", text: intent.copiedCall ?? s.operatorCall }); if (intent.kind === "send-exchange" || intent.kind === "send-call-and-exchange") return reduceSpQso(state, { type: "operator-exchange", call: intent.call ?? s.stationCall, rst: intent.rst ?? "599", exchange: intent.serial ?? "" }); if (intent.kind === "request-again") return reduceSpQso(state, { type: "operator-agn" }); if (intent.kind === "request-call") return reduceSpQso(state, { type: "operator-call-request" }); if (intent.kind === "request-number") return reduceSpQso(state, { type: "operator-number-request" }); if (intent.kind === "send-tu") return reduceSpQso(state, { type: "operator-tu" }); return { state, effects: [] }; }
  if (event.type === "reply-timeout") { const timedOut = { ...state, patience: state.patience - 1 }; if (timedOut.patience <= 0) return failCallCopy(timedOut); if (state.phase === "receiving-exchange" || state.phase === "station-requesting-number") return s.profile.repeatsExchangeOnTimeout ? station(timedOut, `${s.operatorCall} 5NN ${s.exchange}`, "exchange", "awaiting-reply", "need-operator-number", true) : station(timedOut, "NR?", "number", "station-requesting-number", "need-operator-number", true); if (state.phase === "station-requesting-call" || state.phase === "station-requesting-again") return station(timedOut, "CALL?", "call", "station-requesting-call", "need-operator-call", true); return { state, effects: [] }; }
  if (event.type === "operator-call") { if (state.phase !== "listening-cq" && state.phase !== "station-requesting-call") return { state, effects: [] }; const text = event.text || s.operatorCall; const transition = op(state, text, state.phase === "station-requesting-call" ? "requested-call" : "initial-call", "CALLING"); return withTimeoutCancel({ ...transition, state: { ...transition.state, transmittedOperatorCall: text } }); }
  if (event.type === "operator-repeat") { const pending = state.phase === "station-requesting-again" ? "requested-again" : state.phase === "station-requesting-number" ? "requested-number" : undefined; return pending && state.lastOperatorText ? withTimeoutCancel(op(state, state.lastOperatorText, pending, "REPETINDO")) : { state, effects: [] }; }
  if (event.type === "operator-send-exchange" || event.type === "operator-exchange") { if (state.phase !== "receiving-exchange" && state.phase !== "station-requesting-number") return { state, effects: [] }; return op(state, `5NN ${state.serial}`, state.phase === "station-requesting-number" ? "requested-number" : "our-exchange", "ENVIANDO INTERCÂMBIO", "sending-our-exchange"); }
  if (event.type === "operator-tu") return { state, effects: [{ type: "play-operator", text: "TU" }] };
  if (event.type === "operator-agn" && state.lastStationText) return withTimeoutCancel(op(state, "AGN", "agn-request", "AGN", "calling-station", state.phase, state.logical));
  if (event.type === "operator-number-request") return withTimeoutCancel(op(state, "NR?", "number-request", "NR?", "calling-station", state.phase, state.logical));
  if (event.type === "operator-call-request") return withTimeoutCancel(op(state, "CALL?", "call-request", "CALL?", "calling-station", state.phase, state.logical));
  if (event.type === "station-finished" && (event.message === "b4" || event.message === "qrl" || event.message === "qsy") && state.phase === "awaiting-tu") return endWithoutQso(state, event.message === "b4" ? "WORKED" : "FAILED");
  if (event.type === "station-finished" && event.message === "nil" && state.phase === "station-requesting-call") return { state: { ...state, physical: "listening" }, effects: [startReplyTimeout(state)] };
  if (event.type === "station-finished" && event.message === "exchange" && state.phase === "awaiting-reply") return { state: { ...state, phase: "receiving-exchange", logical: "need-operator-number", physical: "listening" }, effects: [{ type: "status", label: "RECEBENDO INTERCÂMBIO" }, startReplyTimeout(state)] };
  if (event.type === "station-finished" && ((event.message === "number" && state.phase === "station-requesting-number") || (event.message === "call" && state.phase === "station-requesting-call") || (event.message === "agn" && state.phase === "station-requesting-again"))) return { state: { ...state, physical: "listening" }, effects: [startReplyTimeout(state)] };
  if (event.type === "station-finished" && event.message === "final" && state.phase === "awaiting-tu" && !state.registered) return { state: { ...state, phase: "completed", logical: "completed", physical: "listening", registered: true }, effects: [{ type: "status", label: "QSO CONCLUÍDO" }, { type: "register-qso", result: "OK" }, { type: "mark-worked" }, { type: "update-spot-status", status: "WORKED" }, { type: "clear-entry" }] };
  if (event.type === "operator-finished" && (state.pendingOperator === "our-exchange" || state.pendingOperator === "requested-number")) { const after = { ...state, physical: "copying" as const, pendingOperator: undefined }; if (state.pendingOperator === "our-exchange" && (has(after, "request-number") || has(after, "repeat-exchange"))) return station(consume(after, has(after, "request-number") ? "request-number" : "repeat-exchange"), "NR?", "number", "station-requesting-number", "need-operator-number"); return station(after, finalAcknowledgement(after, s), "final", "awaiting-tu", "closing"); }
  if (event.type === "operator-finished") { const pending = state.pendingOperator; const after: SpQsoState = { ...state, physical: "copying", pendingOperator: undefined, callAttempts: state.callAttempts + (pending === "initial-call" ? 1 : 0) }; if (pending === "agn-request") return station(after, after.lastStationText ?? "", "exchange", after.returnPhase ?? "receiving-exchange", after.logical, true); if (pending === "number-request") return station(after, `5NN ${s.exchange}`, "number", after.returnPhase ?? "receiving-exchange", after.logical, true); if (pending === "call-request") return station(after, `DE ${s.stationCall} ${s.stationCall}`, "call", after.returnPhase ?? "receiving-exchange", after.logical, true); if (pending === "initial-call" || pending === "requested-call" || pending === "requested-again") return respondToOperatorCall(after, s); if (pending === "our-exchange") return has(after, "request-number") || has(after, "repeat-exchange") ? station(consume(after, has(after, "request-number") ? "request-number" : "repeat-exchange"), "NR?", "number", "station-requesting-number", "need-operator-number") : station(after, "TU", "tu", "awaiting-tu", "closing"); if (pending === "requested-number") return station(after, "TU", "tu", "awaiting-tu", "closing"); }
  if (event.type === "station-finished") { if (event.message === "busy" && state.phase === "station-busy") return { state: { ...state, phase: "listening-cq", logical: "calling-cq", physical: "listening" }, effects: [{ type: "status", label: "CQ" }, { type: "restart-cq" }] }; if (event.message === "exchange" && state.phase === "awaiting-reply") return { state: { ...state, phase: "receiving-exchange", logical: "need-operator-number", physical: "listening" }, effects: [{ type: "status", label: "RECEBENDO INTERCÂMBIO" }] }; if ((event.message === "exchange" || event.message === "number" || event.message === "call") && state.phase === "receiving-exchange") return { state: { ...state, physical: "listening", returnPhase: undefined }, effects: [] }; if (event.message === "tu" && state.phase === "awaiting-tu" && !state.registered) return { state: { ...state, phase: "completed", logical: "completed", physical: "listening", registered: true }, effects: [{ type: "status", label: "QSO CONCLUÍDO" }, { type: "register-qso", result: "OK" }, { type: "mark-worked" }, { type: "update-spot-status", status: "WORKED" }, { type: "clear-entry" }] }; }
  if (event.type === "station-finished" && event.message === "exchange" && state.phase === "awaiting-reply") return { state: { ...state, phase: "receiving-exchange", logical: "need-operator-number", physical: "listening" }, effects: [{ type: "status", label: "RECEBENDO INTERCÂMBIO" }, startReplyTimeout(state)] };
  if (event.type === "station-finished" && ((event.message === "number" && state.phase === "station-requesting-number") || (event.message === "call" && state.phase === "station-requesting-call") || (event.message === "agn" && state.phase === "station-requesting-again"))) return { state: { ...state, physical: "listening" }, effects: [startReplyTimeout(state)] };
  if (event.type === "station-finished" && event.message === "final" && state.phase === "awaiting-tu" && !state.registered) return { state: { ...state, phase: "completed", logical: "completed", physical: "listening", registered: true }, effects: [{ type: "status", label: "QSO CONCLUÍDO" }, { type: "register-qso", result: "OK" }, { type: "mark-worked" }, { type: "update-spot-status", status: "WORKED" }, { type: "clear-entry" }] };
  return { state, effects: [] };
}
