export type CallMatch = "exact" | "almost" | "wrong";
export type QsoCheck = "OK" | "CALL" | "RST" | "NR" | "NIL" | "DUP";
export type SpLogicalState = "waiting-for-tune" | "calling-cq" | "busy-with-other-station" | "need-operator-call" | "need-operator-number" | "need-operator-call-and-number" | "ready-to-acknowledge" | "closing" | "cooldown" | "completed" | "failed" | "aborted";
export type SpPhysicalState = "listening" | "copying" | "preparing" | "sending";
export type SpQsoPhase = "idle" | "listening-cq" | "station-busy" | "calling-station" | "awaiting-reply" | "receiving-exchange" | "sending-our-exchange" | "station-requesting-call" | "station-requesting-number" | "station-requesting-again" | "awaiting-tu" | "completed" | "failed" | "aborted";
export type SpIncident = "busy" | "ignore-first-call" | "request-agn" | "request-call" | "request-number" | "repeat-exchange" | "partial-operator-call";
export type SpStationMessage = "busy" | "exchange" | "agn" | "call" | "number" | "tu";

export interface SpQsoScenario { id: string; stationCall: string; spottedCallsign: string; operatorCall: string; exchange: string; rst: string; wpm: number; toneOffsetHz: number; signalLevel: number; skill: 1 | 2 | 3; patience: number; responseDelayMs: number; initialBehavior: "normal" | "busy" | "ignores-first-call"; operatorCallCopy: CallMatch; operatorExchangeCopy: CallMatch; repeatCount: 1 | 2; incidents: readonly SpIncident[]; }
export interface SpQsoState { phase: SpQsoPhase; logical: SpLogicalState; physical: SpPhysicalState; scenario?: SpQsoScenario; serial: string; patience: number; callAttempts: number; usedIncidents: readonly SpIncident[]; pendingOperator?: "initial-call" | "requested-call" | "requested-again" | "our-exchange" | "requested-number" | "agn-request" | "number-request" | "call-request"; returnPhase?: SpQsoPhase; returnLogical?: SpLogicalState; lastOperatorText?: string; lastStationText?: string; registered: boolean; }
export type SpQsoEffect = { type: "play-operator"; text: string } | { type: "play-station"; text: string; message: SpStationMessage; delayMs?: number } | { type: "status"; label: string } | { type: "register-qso"; result: QsoCheck } | { type: "record-error" } | { type: "mark-worked" } | { type: "restart-cq" } | { type: "clear-entry" } | { type: "update-spot-status"; status: "BUSY" | "WORKED" | "FAILED" };
export type SpQsoEvent = { type: "start"; scenario: SpQsoScenario; serial: string } | { type: "operator-call" } | { type: "operator-exchange"; call: string; rst: string; exchange: string } | { type: "operator-send-exchange" } | { type: "operator-tu" } | { type: "operator-agn" } | { type: "operator-number-request" } | { type: "operator-call-request" } | { type: "operator-repeat" } | { type: "operator-finished" } | { type: "station-finished"; message: SpStationMessage } | { type: "reply-timeout" } | { type: "tuned-out" } | { type: "abort" };
export interface SpQsoTransition { state: SpQsoState; effects: readonly SpQsoEffect[]; }
export const INITIAL_SP_QSO_STATE: SpQsoState = { phase: "idle", logical: "waiting-for-tune", physical: "listening", serial: "001", patience: 0, callAttempts: 0, usedIncidents: [], registered: false };

const normalize = (value: string): string => value.trim().toUpperCase().replace(/[^A-Z0-9/?]/g, "");
const editDistance = (left: string, right: string): number => { const row = Array.from({ length: right.length + 1 }, (_, i) => i); for (let i = 1; i <= left.length; i += 1) { let previous = row[0]!; row[0] = i; for (let j = 1; j <= right.length; j += 1) { const saved = row[j]!; const same = left[i - 1] === "?" || left[i - 1] === right[j - 1]; row[j] = Math.min(row[j]! + 1, row[j - 1]! + 1, previous + (same ? 0 : 1)); previous = saved; } } return row[right.length]!; };
export function compareCallsign(entered: string, expected: string): CallMatch { const input = normalize(entered); const target = normalize(expected); if (input.length < 2) return "wrong"; if (input === target) return "exact"; const known = input.replaceAll("?", ""); if (known.length >= 2 && (target.includes(known) || input.includes(target))) return "almost"; return editDistance(input, target) <= 1 ? "almost" : "wrong"; }
export function checkSpQso(entry: { call: string; rst: string; exchange: string }, scenario: SpQsoScenario, duplicate = false): QsoCheck { if (duplicate) return "DUP"; const call = compareCallsign(entry.call, scenario.stationCall); if (call !== "exact") return call === "almost" ? "CALL" : "NIL"; if (normalize(entry.rst) !== scenario.rst) return "RST"; return normalize(entry.exchange) === scenario.exchange ? "OK" : "NR"; }
const has = (state: SpQsoState, item: SpIncident): boolean => state.scenario?.incidents.includes(item) === true && !state.usedIncidents.includes(item);
const consume = (state: SpQsoState, item: SpIncident): SpQsoState => ({ ...state, usedIncidents: state.usedIncidents.includes(item) ? state.usedIncidents : [...state.usedIncidents, item] });
const station = (state: SpQsoState, text: string, message: SpStationMessage, phase: SpQsoPhase, logical: SpLogicalState, delayed = false): SpQsoTransition => ({ state: { ...state, phase, logical: delayed ? state.returnLogical ?? logical : logical, physical: "sending", lastStationText: text }, effects: [{ type: "play-station", text, message, ...(delayed ? { delayMs: state.scenario?.responseDelayMs } : {}) }] });
const op = (state: SpQsoState, text: string, pending: NonNullable<SpQsoState["pendingOperator"]>, label: string, phase: SpQsoPhase = "calling-station", returnPhase?: SpQsoPhase, returnLogical?: SpLogicalState): SpQsoTransition => ({ state: { ...state, phase, logical: phase === "sending-our-exchange" ? "need-operator-number" : "need-operator-call", physical: "sending", pendingOperator: pending, returnPhase, returnLogical, lastOperatorText: text }, effects: [{ type: "play-operator", text }, { type: "status", label }] });

export function createSpQsoScenario(stationCall: string, operatorCall: string, exchange: string, random: () => number, details: Partial<Pick<SpQsoScenario, "id" | "wpm" | "toneOffsetHz" | "signalLevel">> = {}): SpQsoScenario { const choices: SpIncident[] = ["busy", "ignore-first-call", "request-agn", "request-call", "request-number", "repeat-exchange", "partial-operator-call"]; const roll = random(); const count = roll < .12 ? 2 : roll < .4 ? 1 : 0; const incidents: SpIncident[] = []; while (incidents.length < count) { const item = choices[Math.floor(random() * choices.length)]!; if (!incidents.includes(item)) incidents.push(item); } return { id: details.id ?? normalize(stationCall), stationCall: normalize(stationCall), spottedCallsign: normalize(stationCall), operatorCall: normalize(operatorCall), exchange: normalize(exchange).padStart(3, "0"), rst: "599", wpm: details.wpm ?? 30, toneOffsetHz: details.toneOffsetHz ?? 0, signalLevel: details.signalLevel ?? 0, skill: 2, patience: 4, responseDelayMs: 250, initialBehavior: incidents.includes("busy") ? "busy" : incidents.includes("ignore-first-call") ? "ignores-first-call" : "normal", operatorCallCopy: incidents.includes("partial-operator-call") ? "almost" : "exact", operatorExchangeCopy: incidents.includes("repeat-exchange") ? "almost" : "exact", repeatCount: 1, incidents }; }

export function reduceSpQso(state: SpQsoState, event: SpQsoEvent): SpQsoTransition {
  if (event.type === "abort" || event.type === "tuned-out") return { state: { ...state, phase: "aborted", logical: "aborted", physical: "listening", pendingOperator: undefined }, effects: [{ type: "status", label: "QSO ABORTADO" }, { type: "clear-entry" }] };
  if (event.type === "start") return { state: { phase: "listening-cq", logical: "calling-cq", physical: "listening", scenario: event.scenario, serial: event.serial, patience: event.scenario.patience, callAttempts: 0, usedIncidents: [], registered: false }, effects: [{ type: "status", label: "CQ" }, { type: "clear-entry" }] };
  const s = state.scenario; if (!s || ["idle", "completed", "failed", "aborted"].includes(state.phase)) return { state, effects: [] };
  if (event.type === "reply-timeout") { const patience = state.patience - 1; return patience > 0 ? { state: { ...state, patience }, effects: [{ type: "status", label: "WAIT" }] } : { state: { ...state, phase: "failed", logical: "failed", patience }, effects: [{ type: "status", label: "FAILED" }, { type: "update-spot-status", status: "FAILED" }, { type: "restart-cq" }] }; }
  if (event.type === "operator-call") { if (state.phase !== "listening-cq" && state.phase !== "station-requesting-call") return { state, effects: [] }; return op(state, s.operatorCall, state.phase === "station-requesting-call" ? "requested-call" : "initial-call", "CALLING"); }
  if (event.type === "operator-repeat") { const pending = state.phase === "station-requesting-again" ? "requested-again" : state.phase === "station-requesting-number" ? "requested-number" : undefined; return pending && state.lastOperatorText ? op(state, state.lastOperatorText, pending, "REPETINDO") : { state, effects: [] }; }
  if (event.type === "operator-send-exchange" || event.type === "operator-exchange") { if (state.phase !== "receiving-exchange" && state.phase !== "station-requesting-number") return { state, effects: [] }; return op(state, `5NN ${state.serial}`, state.phase === "station-requesting-number" ? "requested-number" : "our-exchange", "ENVIANDO INTERCÂMBIO", "sending-our-exchange"); }
  if (event.type === "operator-tu") return { state, effects: [{ type: "play-operator", text: "TU" }] };
  if (event.type === "operator-agn" && state.lastStationText) return op(state, "AGN", "agn-request", "AGN", "calling-station", state.phase, state.logical);
  if (event.type === "operator-number-request") return op(state, "NR?", "number-request", "NR?", "calling-station", state.phase, state.logical);
  if (event.type === "operator-call-request") return op(state, "CALL?", "call-request", "CALL?", "calling-station", state.phase, state.logical);
  if (event.type === "operator-finished") { const pending = state.pendingOperator; const after: SpQsoState = { ...state, physical: "copying", pendingOperator: undefined, callAttempts: state.callAttempts + (pending === "initial-call" ? 1 : 0) }; if (pending === "agn-request") return station(after, after.lastStationText ?? "", "exchange", after.returnPhase ?? "receiving-exchange", after.logical, true); if (pending === "number-request") return station(after, `5NN ${s.exchange}`, "number", after.returnPhase ?? "receiving-exchange", after.logical, true); if (pending === "call-request") return station(after, `DE ${s.stationCall} ${s.stationCall}`, "call", after.returnPhase ?? "receiving-exchange", after.logical, true); if (pending === "initial-call") { if (has(after, "busy")) return station(consume(after, "busy"), "W1AW 5NN 047 TU", "busy", "station-busy", "busy-with-other-station"); if (has(after, "ignore-first-call")) return { state: { ...consume(after, "ignore-first-call"), phase: "listening-cq", logical: "calling-cq", physical: "listening" }, effects: [{ type: "status", label: "SEM RESPOSTA" }, { type: "restart-cq" }] }; if (has(after, "request-agn")) return station(consume(after, "request-agn"), "AGN?", "agn", "station-requesting-again", "need-operator-call"); if (has(after, "request-call") || s.operatorCallCopy === "almost") return station(consume(after, "request-call"), `${s.operatorCall.slice(0, -1)}? CALL?`, "call", "station-requesting-call", "need-operator-call"); return station(after, `${s.operatorCall} 5NN ${s.exchange}`, "exchange", "awaiting-reply", "need-operator-call-and-number"); } if (pending === "requested-call" || pending === "requested-again") return station(after, `${s.operatorCall} 5NN ${s.exchange}`, "exchange", "awaiting-reply", "need-operator-number"); if (pending === "our-exchange") return has(after, "request-number") || has(after, "repeat-exchange") ? station(consume(after, has(after, "request-number") ? "request-number" : "repeat-exchange"), "NR?", "number", "station-requesting-number", "need-operator-number") : station(after, "TU", "tu", "awaiting-tu", "closing"); if (pending === "requested-number") return station(after, "TU", "tu", "awaiting-tu", "closing"); }
  if (event.type === "station-finished") { if (event.message === "busy" && state.phase === "station-busy") return { state: { ...state, phase: "listening-cq", logical: "calling-cq", physical: "listening" }, effects: [{ type: "status", label: "CQ" }, { type: "restart-cq" }] }; if (event.message === "exchange" && state.phase === "awaiting-reply") return { state: { ...state, phase: "receiving-exchange", logical: "need-operator-number", physical: "listening" }, effects: [{ type: "status", label: "RECEBENDO INTERCÂMBIO" }] }; if ((event.message === "exchange" || event.message === "number" || event.message === "call") && state.phase === "receiving-exchange") return { state: { ...state, physical: "listening", returnPhase: undefined }, effects: [] }; if (event.message === "tu" && state.phase === "awaiting-tu" && !state.registered) return { state: { ...state, phase: "completed", logical: "completed", physical: "listening", registered: true }, effects: [{ type: "status", label: "QSO CONCLUÍDO" }, { type: "register-qso", result: "OK" }, { type: "mark-worked" }, { type: "update-spot-status", status: "WORKED" }, { type: "clear-entry" }] }; }
  return { state, effects: [] };
}
