import { BANDMAP_40M, BandmapEngine, clampStationCount, clampWpm, QSO_TRAINING_STATES, restoreRxEnvironment, RX_PRESETS, SandPSessionController, VirtualVfo, type AdvancedAudioSettings, type BandmapStation, type OperatingMode, type QsoTrainingState, type RxEnvironmentSettings, type RxPreset, type StationCount } from "@gadx/runner-core";
import { BandmapView } from "./bandmap-view";
import { loadCallsignDatabase, selectCallsigns } from "./callsign-source";
import { CwAudioEngine } from "./cw-audio";

interface TrainingPreferences { wpm: number; minWpm: number; maxWpm: number; toneHz: number; volume: number; adaptive: boolean; operatorCall: string; durationMinutes: 5 | 10 | 15 | 30 | 60; rxEnvironment: boolean; rxPreset: RxPreset; bandNoiseLevel: number; qrnLevel: number; qrmLevel: number; signalVariation: boolean; frequencyVariation: boolean; slowFading: boolean; stationSpeedVariation: boolean; stationCount: StationCount; }
interface SessionRecord { endedAt: string; seconds: number; qsos: number; errors: number; accuracy: number; rate: number; bestStreak: number; initialWpm: number; finalWpm: number; }
interface TrainingStorage { preferences: TrainingPreferences; bestAccuracy: number; bestStreak: number; bestRate: number; history: SessionRecord[]; }
const storageKey = "gadx-cw-runner-training";
const defaults: TrainingPreferences = { wpm: 30, minWpm: 10, maxWpm: 60, toneHz: 600, volume: 0.4, adaptive: false, operatorCall: "PY5XT", durationMinutes: 10, rxEnvironment: false, rxPreset: "normal", bandNoiseLevel: RX_PRESETS.normal.bandNoiseLevel, qrnLevel: RX_PRESETS.normal.qrnLevel, qrmLevel: RX_PRESETS.normal.qrmLevel, signalVariation: false, frequencyVariation: false, slowFading: false, stationSpeedVariation: false, stationCount: 1 };
function loadStorage(): TrainingStorage { try { const saved = JSON.parse(localStorage.getItem(storageKey) ?? "{}") as Partial<TrainingStorage> & { preferences?: Partial<TrainingPreferences> & { advancedAudio?: boolean } }; const savedPreferences = saved.preferences; const restoredRx = restoreRxEnvironment(savedPreferences ? { enabled: savedPreferences.rxEnvironment, preset: savedPreferences.rxPreset, bandNoiseLevel: savedPreferences.bandNoiseLevel, qrnLevel: savedPreferences.qrnLevel, qrmLevel: savedPreferences.qrmLevel, stationCount: savedPreferences.stationCount } : undefined, savedPreferences?.advancedAudio); return { preferences: { ...defaults, ...savedPreferences, rxEnvironment: restoredRx.enabled, rxPreset: restoredRx.preset, bandNoiseLevel: restoredRx.bandNoiseLevel, qrnLevel: restoredRx.qrnLevel, qrmLevel: restoredRx.qrmLevel, stationCount: restoredRx.stationCount }, bestAccuracy: saved.bestAccuracy ?? 0, bestStreak: saved.bestStreak ?? 0, bestRate: saved.bestRate ?? 0, history: saved.history ?? [] }; } catch { return { preferences: defaults, bestAccuracy: 0, bestStreak: 0, bestRate: 0, history: [] }; } }
let stored = loadStorage(); let preferences = stored.preferences;
function saveStorage(): void { localStorage.setItem(storageKey, JSON.stringify(stored)); }

const app = document.querySelector<HTMLDivElement>("#app");
if (!app) throw new Error("Elemento #app não encontrado.");
app.innerHTML = `
  <main class="contest-app" aria-label="Araucaria CW Runner">
    <header class="app-header"><img class="brand-mark" src="${import.meta.env.BASE_URL}logo-gadx.png" alt="Araucaria DX Group" /><div class="brand"><strong>ARAUCARIA CW RUNNER</strong><span>Morse Code Training Platform</span></div><div class="header-actions"><button id="audio-test" aria-label="Testar áudio">♫</button><button id="settings-icon" aria-label="Configurações">⚙</button></div></header>
    <div class="app-layout">
      <aside class="left-rail" aria-label="Velocidade, taxa e resumo da banda"><section class="speed-panel"><div class="meter"><h2>CW SPEED<small>WPM</small></h2><div class="speed-values"><span>50</span><span>45</span><span>40</span><span>35</span><button class="selected-speed">30</button><span>25</span><span>20</span><span>18</span><span>15</span></div></div><div class="meter rate-meter"><h2>RATE<small><output id="instant-rate-value">0</output> QSO/H</small></h2><div class="speed-values"><span data-rate="260">260</span><span data-rate="220">220</span><span data-rate="180">180</span><span data-rate="140">140</span><span data-rate="100">100</span><span data-rate="60">60</span><span data-rate="40">40</span><span data-rate="20">20</span><span class="selected-rate" data-rate="0" aria-current="true">0</span></div></div></section><section class="band-summary-card" aria-label="Resumo das condições da banda"><h2><span>CONDIÇÕES DA BANDA</span><button id="conditions-toggle" class="conditions-toggle" type="button" aria-controls="conditions-panel" aria-expanded="false" aria-label="Abrir condições da banda"><span aria-hidden="true">☰</span></button></h2><dl><div><dt>AMBIENTE RX</dt><dd id="summary-rx">DESLIGADO</dd></div><div><dt>PRESET</dt><dd id="summary-preset">NORMAL</dd></div><div><dt>ESTAÇÕES</dt><dd id="summary-stations">1</dd></div><div><dt>RUÍDO DE BANDA</dt><dd id="summary-band-noise">18%</dd></div><div><dt>QRN / QRM</dt><dd id="summary-qrn-qrm">15% / 0%</dd></div><div><dt>EFEITOS</dt><dd id="summary-effects">NENHUM</dd></div></dl></section></aside>
      <section class="work-area"><section class="entry-window"><div class="entry-fields"><label class="callsign-field">CALLSIGN<input id="callsign" autocomplete="off" autocapitalize="characters" spellcheck="false" autofocus /></label><label>RCV<input id="received-rst" value="599" inputmode="numeric" /></label><label>SERIAL<input id="serial" value="001" readonly /></label><label>EXCHANGE<input id="exchange" inputmode="numeric" /></label></div><div class="operation-row"><button class="mode-button active"><i></i> RUN</button><button class="mode-button"><i></i> S&amp;P</button><span class="divider"></span><button class="pileup-button">PILE-UP <span>▾</span></button><span class="divider"></span><label class="speed-control"><input id="wpm" type="number" min="10" max="60" /> WPM <span>▾</span></label></div><div class="macro-grid"><button id="f1">F1 CQ</button><button id="f2">F2 EXCH</button><button id="f3">F3 TU</button><button id="f4">F4 CALL ESTAÇÃO</button><button id="f5">F5 CALL RECEBIDO</button><button id="f6">F6 REPETIR</button><button id="f7">F7 ?</button><button id="f8">F8 AGN</button><button id="f9">F9 NR?</button><button id="f10">F10 CALL?</button><button>F11 —</button><button id="f12">F12 LIMPAR</button></div><div class="action-row"><button id="stop-button" class="stop-button">ESC PARAR</button><button id="wipe-action">LIMPAR QSO</button><button id="start-button" class="start-button">INICIAR TREINO</button><button id="state-label" disabled>PARADO</button></div><footer id="feedback" aria-live="polite">Pronto. Clique em “Iniciar treino” para liberar o áudio no navegador.</footer><div class="session-stats"><span>QSOs <strong id="valid-qsos">0</strong></span><span>ERROS <strong id="errors">0</strong></span><span>PRECISÃO <strong id="accuracy">--</strong></span><span>SEQUÊNCIA <strong id="streak">0</strong></span><span>WPM <strong id="current-wpm">30</strong></span></div></section><section class="results-area"><article class="log-card"><h2>TRAINING LOG</h2><table><thead><tr><th>HORA</th><th>CALL</th><th>RCV</th><th>EXCH</th><th>RESULTADO</th></tr></thead><tbody id="log-body"><tr class="empty-log"><td colspan="5">Os contatos registrados aparecerão aqui.</td></tr></tbody></table></article><article class="rate-card"><h2>RATE (QSO/H)</h2><div class="bars"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="rate-summary">MÉDIA <strong id="rate-value">0</strong> QSO/H</div></article></section></section>
      <aside class="performance-panel" aria-label="Desempenho da sessão"><div class="score-card"><div class="metric"><span>◷</span><span class="metric-label">TEMPO</span><strong id="timer">00:00</strong></div><div class="metric"><span>▥</span><span class="metric-label">RATE</span><strong id="side-rate">0 <small>QSO/H</small></strong></div><div class="metric"><span class="trophy">♜</span><span class="metric-label">SCORE</span><strong id="score">0</strong></div></div><section id="bandmap-panel" class="bandmap-panel" aria-label="Bandmap simulado de 40 metros" tabindex="-1" hidden><header><strong>GADX VIRTUAL VFO A</strong><output id="bandmap-frequency">7025.00 kHz</output><div><span>40M</span><span>CW</span><span>FILTRO 500 HZ</span><span><output id="bandmap-spot-count">0</output> SPOTS</span></div></header><div id="bandmap-plot" class="bandmap-plot"></div></section></aside>
      <aside id="conditions-panel" class="conditions-panel" aria-label="Configurações das condições da banda"><h2><span>BAND CONDITIONS</span><button id="close-conditions" type="button" aria-label="Fechar condições da banda">×</button></h2><div class="condition-list"><label>AMBIENTE RX <input id="setting-rx-environment" type="checkbox" role="switch" aria-describedby="rx-environment-status" /></label><p id="rx-environment-status" class="rx-environment-status" role="status">AMBIENTE RX DESLIGADO</p><label>VAR. SINAL <input id="setting-signal-variation" type="checkbox" /></label><label>VAR. FREQUÊNCIA <input id="setting-frequency-variation" type="checkbox" /></label><label>FADING LENTO <input id="setting-slow-fading" type="checkbox" /></label><label>WPM VARIÁVEL <input id="setting-speed-variation" type="checkbox" /></label></div><div id="advanced-audio-controls" class="select-list advanced-inline-controls"><label>PRESET<select id="setting-rx-preset"><option value="clean">LIMPA</option><option value="normal">NORMAL</option><option value="noisy">RUÍDA</option><option value="contest">CONTEST</option></select></label><label>ESTAÇÕES<select id="setting-station-count"><option value="1">1 estação</option><option value="2">2 estações</option><option value="3">3 estações</option></select></label><label class="range-control"><span>RUÍDO DE BANDA <output id="setting-band-noise-value">18%</output></span><input id="setting-band-noise" type="range" min="0" max="100" step="1" /></label><label class="range-control"><span>QRN <output id="setting-qrn-value">15%</output></span><input id="setting-qrn" type="range" min="0" max="100" step="1" /></label><label class="range-control"><span>QRM <output id="setting-qrm-value">0%</output></span><input id="setting-qrm" type="range" min="0" max="100" step="1" /></label></div></aside>
    </div>
  </main>
  <dialog id="settings-dialog" class="modal"><form id="settings-form" method="dialog"><header><h2>CONFIGURAÇÕES DO TREINO</h2><button value="cancel" aria-label="Fechar">×</button></header><div class="settings-grid"><label>WPM inicial<input id="setting-wpm" type="number" min="10" max="60" /></label><label>Limite mínimo<input id="setting-min-wpm" type="number" min="10" max="60" /></label><label>Limite máximo<input id="setting-max-wpm" type="number" min="10" max="60" /></label><label>Frequência do tom<input id="setting-tone" type="number" min="300" max="1000" step="10" /></label><label class="volume-setting"><span>Volume <output id="setting-volume-value">40%</output></span><input id="setting-volume" type="range" min="0" max="100" step="1" /></label><label class="switch-setting">Velocidade adaptativa<input id="setting-adaptive" type="checkbox" /></label><label>Seu indicativo<input id="setting-operator" maxlength="12" /></label><label>Duração da sessão<select id="setting-duration"><option value="5">5 minutos</option><option value="10">10 minutos</option><option value="15">15 minutos</option><option value="30">30 minutos</option><option value="60">60 minutos</option></select></label></div><p class="settings-note">Os efeitos e a quantidade de estações ficam no painel Band Conditions. Com Ambiente RX desligado, o sinal permanece limpo.</p><section class="credits-panel" aria-label="Sobre e créditos"><h3>SOBRE / CRÉDITOS</h3><p id="callsign-base-status">Base CQ WW CW 2025 — 8.109 estações</p><p>Fonte de indicativos: participantes do CQ World Wide DX Contest CW 2025.</p></section><footer><button value="cancel">CANCELAR</button><button id="save-settings" value="default" class="save-button">SALVAR CONFIGURAÇÕES</button></footer></form></dialog>
  <dialog id="summary-dialog" class="modal summary-modal"><section><header><h2>SESSÃO ENCERRADA</h2><button id="close-summary" type="button" aria-label="Fechar resumo da sessão">×</button></header><div id="summary-content" class="summary-grid"></div><div class="personal-bests">Melhores locais: precisão <strong id="best-accuracy">0%</strong> · sequência <strong id="best-streak">0</strong> · taxa <strong id="best-rate">0</strong> QSO/H</div><footer><button id="clear-history">APAGAR SOMENTE HISTÓRICO</button><button id="new-session" class="save-button">NOVA SESSÃO</button></footer></section></dialog>`;

const element = <T extends HTMLElement>(selector: string): T => document.querySelector<T>(selector)!;
const feedback = element<HTMLElement>("#feedback"), callsign = element<HTMLInputElement>("#callsign"), receivedRst = element<HTMLInputElement>("#received-rst"), serial = element<HTMLInputElement>("#serial"), exchange = element<HTMLInputElement>("#exchange"), wpmInput = element<HTMLInputElement>("#wpm"), stateLabel = element<HTMLButtonElement>("#state-label"), startButton = element<HTMLButtonElement>("#start-button"), settingsDialog = element<HTMLDialogElement>("#settings-dialog"), summaryDialog = element<HTMLDialogElement>("#summary-dialog");
const conditionsPanel = element<HTMLElement>("#conditions-panel"), conditionsToggle = element<HTMLButtonElement>("#conditions-toggle");
const workArea = element<HTMLElement>(".work-area"), performancePanel = element<HTMLElement>(".performance-panel");
const sessionMetrics = document.createElement("section");
sessionMetrics.className = "session-metrics";
sessionMetrics.setAttribute("aria-label", "Indicadores da sessão");
sessionMetrics.append(performancePanel.querySelector<HTMLElement>(".score-card")!);
workArea.prepend(sessionMetrics);
const modeButtons = [...document.querySelectorAll<HTMLButtonElement>(".mode-button")];
const runModeButton = modeButtons[0]!, sandpModeButton = modeButtons[1]!;
runModeButton.id = "mode-run"; sandpModeButton.id = "mode-sandp";
runModeButton.setAttribute("aria-pressed", "true"); sandpModeButton.setAttribute("aria-pressed", "false");
conditionsPanel.setAttribute("inert", "");
callsign.setAttribute("aria-describedby", "feedback");
callsign.setAttribute("aria-keyshortcuts", "Enter");
receivedRst.setAttribute("aria-keyshortcuts", "Enter");
exchange.setAttribute("aria-keyshortcuts", "Enter");
element<HTMLButtonElement>("#stop-button").setAttribute("aria-keyshortcuts", "Escape");
element<HTMLButtonElement>("#f12").setAttribute("aria-keyshortcuts", "F12");
for (let number = 1; number <= 10; number += 1) element<HTMLButtonElement>(`#f${number}`).setAttribute("aria-keyshortcuts", `F${number}`);
const unavailableButtons = document.querySelectorAll<HTMLButtonElement>(".pileup-button, .macro-grid button:nth-child(11)");
unavailableButtons.forEach((button) => { button.disabled = true; button.title = "Não disponível nesta versão"; });
settingsDialog.setAttribute("aria-labelledby", "settings-title");
element<HTMLElement>("#settings-dialog h2").id = "settings-title";
summaryDialog.setAttribute("aria-labelledby", "summary-title");
element<HTMLElement>("#summary-dialog h2").id = "summary-title";
let audioContext: AudioContext | undefined; let audioEngine: CwAudioEngine | undefined; let state: QsoTrainingState = QSO_TRAINING_STATES.STOPPED; let operatingMode: OperatingMode = "RUN"; let sessionActive = false; let stationCallsign = ""; let stationCallsigns: string[] = []; let callsignDatabase: readonly string[] = []; let callRequestId = 0; let qsoSerial = 1; let validQsos = 0; let errors = 0; let streak = 0; let bestSessionStreak = 0; let answerHistory: boolean[] = []; let qsoCompletedAt: number[] = []; let sessionStartedAt = 0; let initialWpm = preferences.wpm; let timerId: number | undefined; let scheduledAction: number | undefined; let sessionEndId: number | undefined; let sessionSaved = false;
const bandmapEngine = new BandmapEngine();
const virtualVfo = new VirtualVfo();
let bandmapView: BandmapView;
const sandpController = new SandPSessionController(bandmapEngine, virtualVfo, {
  stopCw: () => audioEngine?.stop(),
  playCq: (station) => playSandPCq(station),
  schedule: (action, delayMs) => window.setTimeout(action, delayMs),
  cancelSchedule: (handle) => window.clearTimeout(handle as number),
  onSelection: (station) => showTunedStation(station),
});
bandmapView = new BandmapView(element<HTMLElement>("#bandmap-panel"), bandmapEngine, virtualVfo, { select: (stationId, fillCallsign) => selectBandmapStation(stationId, fillCallsign) });

function running(): boolean { return sessionActive; } function formatSerial(): string { return String(qsoSerial).padStart(3, "0"); } function currentWpm(): number { return clampWpm(Number(wpmInput.value)); } function elapsedSeconds(): number { return sessionStartedAt ? Math.floor((Date.now() - sessionStartedAt) / 1000) : 0; } function rate(): number { const elapsed = elapsedSeconds(); return elapsed ? Math.round((validQsos * 3600) / elapsed) : 0; } function instantRate(): number { const recent = qsoCompletedAt.slice(-6); if (recent.length < 2) return 0; const elapsedHours = (recent.at(-1)! - recent[0]!) / 3_600_000; return elapsedHours > 0 ? Math.min(260, Math.round((recent.length - 1) / elapsedHours)) : 260; } function accuracy(): number { return validQsos + errors ? Math.round((validQsos / (validQsos + errors)) * 100) : 0; }
function setFeedback(message: string, result?: "correct" | "incorrect"): void { feedback.textContent = message; feedback.className = result ? `feedback-${result}` : ""; } function setState(next: QsoTrainingState): void { state = next; stateLabel.textContent = next; }
function updateRateMeter(): void { const current = instantRate(); element<HTMLOutputElement>("#instant-rate-value").value = String(current); const steps = [...document.querySelectorAll<HTMLElement>(".rate-meter [data-rate]")]; const selected = steps.reduce((closest, step) => Math.abs(Number(step.dataset.rate) - current) < Math.abs(Number(closest.dataset.rate) - current) ? step : closest); steps.forEach((step) => { const active = step === selected; step.classList.toggle("selected-rate", active); if (active) step.setAttribute("aria-current", "true"); else step.removeAttribute("aria-current"); }); }
function updateUi(): void { const elapsed = elapsedSeconds(); const wpm = currentWpm(); element<HTMLElement>("#timer").textContent = `${String(Math.floor(elapsed / 60)).padStart(2, "0")}:${String(elapsed % 60).padStart(2, "0")}`; element<HTMLElement>("#valid-qsos").textContent = String(validQsos); element<HTMLElement>("#errors").textContent = String(errors); element<HTMLElement>("#accuracy").textContent = validQsos + errors ? `${accuracy()}%` : "--"; element<HTMLElement>("#streak").textContent = String(streak); element<HTMLElement>("#current-wpm").textContent = String(wpm); element<HTMLElement>("#rate-value").textContent = String(rate()); element<HTMLElement>("#side-rate").innerHTML = `${rate()} <small>QSO/H</small>`; element<HTMLElement>("#score").textContent = String(validQsos * 100); updateRateMeter(); }
async function unlockAudio(): Promise<boolean> {
  if (!window.AudioContext) { setFeedback("Este navegador não oferece suporte ao áudio CW.", "incorrect"); return false; }
  try { audioContext ??= new AudioContext(); await audioContext.resume(); } catch { setFeedback("O navegador bloqueou o áudio. Clique em Iniciar treino ou na nota musical para liberá-lo; não é exibida uma solicitação de permissão.", "incorrect"); return false; }
  if (audioContext.state !== "running") { setFeedback("O áudio ainda está bloqueado pelo navegador. Clique novamente em Iniciar treino e verifique o volume.", "incorrect"); return false; }
  audioEngine ??= new CwAudioEngine(audioContext);
  audioEngine.setVolume(preferences.volume);
  return true;
}
async function testAudio(volume = preferences.volume, toneHz = preferences.toneHz): Promise<void> {
  if (!await unlockAudio() || !audioEngine) return;
  if (volume <= 0) { setFeedback("O volume está em zero. Ajuste-o em Configurações.", "incorrect"); return; }
  audioEngine.playTestTone(toneHz, volume);
  setFeedback(`Teste de áudio: ${toneHz} Hz, volume ${Math.round(volume * 100)}%.`);
}
function audioSettings(stationCount: StationCount = 1): AdvancedAudioSettings { return { enabled: preferences.rxEnvironment, qrnLevel: preferences.qrnLevel, qrmLevel: preferences.qrmLevel, signalVariation: preferences.signalVariation, frequencyVariation: preferences.frequencyVariation, slowFading: preferences.slowFading, stationSpeedVariation: preferences.stationSpeedVariation, stationCount }; }
function rxEnvironmentSettings(): RxEnvironmentSettings { return { enabled: preferences.rxEnvironment, preset: preferences.rxPreset, bandNoiseLevel: preferences.bandNoiseLevel, qrnLevel: preferences.qrnLevel, qrmLevel: preferences.qrmLevel, stationCount: preferences.stationCount }; }
function updateBandSummary(): void { const active = audioEngine?.environmentActive ?? false; const presetNames: Record<RxPreset, string> = { clean: "LIMPA", normal: "NORMAL", noisy: "RUÍDA", contest: "CONTEST" }; const effects = [[preferences.signalVariation, "SINAL"], [preferences.frequencyVariation, "FREQ."], [preferences.slowFading, "FADING"], [preferences.stationSpeedVariation, "WPM"]] as const; element<HTMLElement>("#summary-rx").textContent = active ? "ATIVO" : preferences.rxEnvironment ? "PRONTO" : "DESLIGADO"; element<HTMLElement>("#summary-preset").textContent = presetNames[preferences.rxPreset]; element<HTMLElement>("#summary-stations").textContent = String(preferences.stationCount); element<HTMLElement>("#summary-band-noise").textContent = `${Math.round(preferences.bandNoiseLevel * 100)}%`; element<HTMLElement>("#summary-qrn-qrm").textContent = `${Math.round(preferences.qrnLevel * 100)}% / ${Math.round(preferences.qrmLevel * 100)}%`; element<HTMLElement>("#summary-effects").textContent = effects.filter(([enabled]) => enabled).map(([, name]) => name).join(", ") || "NENHUM"; }
function updateRxStatus(): void { const status = element<HTMLElement>("#rx-environment-status"); const active = audioEngine?.environmentActive ?? false; status.classList.toggle("active", active); status.textContent = active ? "AMBIENTE RX ATIVO" : preferences.rxEnvironment ? "AMBIENTE RX PRONTO — INICIA COM O TREINO" : "AMBIENTE RX DESLIGADO"; updateBandSummary(); }
function openConditions(): void { conditionsPanel.classList.add("open"); conditionsPanel.removeAttribute("inert"); conditionsToggle.setAttribute("aria-expanded", "true"); conditionsToggle.setAttribute("aria-label", "Fechar condições da banda"); element<HTMLButtonElement>("#close-conditions").focus(); }
function closeConditions(returnFocus = true): void { conditionsPanel.classList.remove("open"); conditionsPanel.setAttribute("inert", ""); conditionsToggle.setAttribute("aria-expanded", "false"); conditionsToggle.setAttribute("aria-label", "Abrir condições da banda"); if (returnFocus) conditionsToggle.focus(); }
function toggleConditions(): void { conditionsPanel.classList.contains("open") ? closeConditions() : openConditions(); }
function stopTransmission(): void { audioEngine?.stopAll(); updateRxStatus(); }
function transmitMany(texts: readonly string[], stationCount: StationCount = 1): number { return audioEngine?.play(texts, { wpm: currentWpm(), toneHz: preferences.toneHz, volume: preferences.volume, advanced: audioSettings(stationCount) }) ?? 0; }
function transmit(text: string): number { return transmitMany([text]); }
function playSandPCq(station: BandmapStation): number { const signalGain = 10 ** (station.signalDb / 40); return audioEngine?.play([`CQ CQ TEST ${station.callsign} ${station.callsign}`], { wpm: station.wpm, toneHz: station.toneHz, volume: preferences.volume, signalGain, advanced: { ...audioSettings(1), enabled: false } }) ?? 0; }
function showTunedStation(station: BandmapStation): void { stationCallsign = station.callsign; stationCallsigns = [station.callsign]; callsign.value = ""; setState(QSO_TRAINING_STATES.RECEIVING_CALLSIGN); audioEngine?.setQrmCallsigns(callsignDatabase, [station.callsign]); bandmapView.render(); setFeedback(`Sintonizado em ${station.frequencyKhz.toFixed(2)} kHz. Escute e confirme o indicativo.`); }
function selectBandmapStation(stationId: string, fillCallsign: boolean): void { let station = sandpController.currentStation?.id === stationId ? sandpController.currentStation : sandpController.tune(stationId); if (!station) return; if (fillCallsign) { callsign.value = station.callsign; callsign.focus(); } }
function updateOperatingModeUi(): void { const sandp = operatingMode === "S_AND_P"; runModeButton.classList.toggle("active", !sandp); sandpModeButton.classList.toggle("active", sandp); runModeButton.setAttribute("aria-pressed", String(!sandp)); sandpModeButton.setAttribute("aria-pressed", String(sandp)); element<HTMLElement>(".app-layout").classList.toggle("sandp-mode", sandp); element<HTMLElement>(".left-rail").hidden = false; performancePanel.hidden = false; performancePanel.classList.toggle("idle", !sandp); element<HTMLElement>("#bandmap-panel").hidden = false; bandmapView.render(); }
function switchOperatingMode(nextMode: OperatingMode): void { if (nextMode === operatingMode) return; if (running()) endSession(false); operatingMode = nextMode; if (nextMode === "RUN") { bandmapEngine.clear(); virtualVfo.tune(BANDMAP_40M.initialKhz); } updateOperatingModeUi(); setFeedback(nextMode === "RUN" ? "Modo RUN selecionado. Inicie o treino para chamar CQ." : "Modo S&P selecionado. Inicie o treino para carregar o Bandmap."); nextMode === "RUN" ? callsign.focus() : element<HTMLElement>("#bandmap-panel").focus(); }
function schedule(action: () => void, delay: number): void { if (scheduledAction) window.clearTimeout(scheduledAction); scheduledAction = window.setTimeout(() => { scheduledAction = undefined; action(); }, delay); }
function clearQso(): void { callsign.value = ""; receivedRst.value = "599"; exchange.value = ""; (state === QSO_TRAINING_STATES.RECEIVING_EXCHANGE ? receivedRst : callsign).focus(); }
function addLog(ok: boolean): void { const body = element<HTMLTableSectionElement>("#log-body"); body.querySelector(".empty-log")?.remove(); const row = document.createElement("tr"); row.innerHTML = `<td>${new Date().toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</td><td>${stationCallsign}</td><td>${receivedRst.value || "—"}</td><td>${exchange.value || "—"}</td><td class="${ok ? "ok" : "not-ok"}">${ok ? "OK" : "ERRO"}</td>`; body.prepend(row); while (body.rows.length > 7) body.deleteRow(-1); }
function adapt(correct: boolean): void { answerHistory.push(correct); answerHistory = answerHistory.slice(-5); if (!preferences.adaptive) return; let next = currentWpm(); if (correct && streak > 0 && streak % 5 === 0) next += 1; if (!correct && answerHistory.filter((value) => !value).length >= 3) next -= 1; next = Math.max(preferences.minWpm, Math.min(preferences.maxWpm, next)); if (next !== currentWpm()) { wpmInput.value = String(next); setFeedback(`Velocidade adaptativa: ${next} WPM.`, correct ? "correct" : "incorrect"); } }
async function receiveCallsigns(count: StationCount, requestId: number): Promise<void> { const [selected, database] = await Promise.all([selectCallsigns(count, [preferences.operatorCall]), loadCallsignDatabase()]); if (!running() || requestId !== callRequestId) return; stationCallsigns = selected; stationCallsign = selected[0]!; audioEngine?.setQrmCallsigns(database, stationCallsigns); setState(QSO_TRAINING_STATES.RECEIVING_CALLSIGN); transmitMany(stationCallsigns, count); callsign.focus(); setFeedback(count === 1 ? "Uma estação respondeu. Copie o indicativo no campo CALLSIGN." : `${count} estações responderam. Copie o sinal principal no campo CALLSIGN.`); }
function callCq(): void { if (!running()) return; const requestId = ++callRequestId; setState(QSO_TRAINING_STATES.CALLING_CQ); const duration = transmit(`CQ CQ ${preferences.operatorCall}`); setFeedback("Chamando CQ..."); schedule(() => { if (!running()) return; const count = preferences.rxEnvironment ? preferences.stationCount : 1; void receiveCallsigns(count, requestId); }, duration + 450); }
function receiveExchange(): void { setState(QSO_TRAINING_STATES.RECEIVING_EXCHANGE); receivedRst.value = "599"; exchange.value = ""; transmit(`599 ${formatSerial()}`); receivedRst.focus(); setFeedback(`Indicativo correto. Receba 599 ${formatSerial()} e preencha RCV e EXCHANGE.`); }
function finishQso(): void { validQsos += 1; qsoCompletedAt.push(Date.now()); streak += 1; bestSessionStreak = Math.max(bestSessionStreak, streak); adapt(true); addLog(true); setState(QSO_TRAINING_STATES.COMPLETED); qsoSerial += 1; serial.value = formatSerial(); clearQso(); updateUi(); const duration = transmit("TU"); setFeedback("QSO registrado. Transmitindo TU e iniciando nova chamada...", "correct"); schedule(callCq, duration + 500); }
function fail(message: string): void { errors += 1; streak = 0; adapt(false); addLog(false); updateUi(); setFeedback(message, "incorrect"); transmit("?"); }
function submit(): void { if (operatingMode === "S_AND_P") { setFeedback("A confirmação e o QSO completo do modo S&P serão habilitados na próxima etapa."); return; } if (state === QSO_TRAINING_STATES.RECEIVING_CALLSIGN) { callsign.value.trim().toUpperCase() === stationCallsign ? receiveExchange() : fail("Indicativo incorreto. Use F6 para repetir."); } else if (state === QSO_TRAINING_STATES.RECEIVING_EXCHANGE) { receivedRst.value.trim() === "599" && exchange.value.trim() === formatSerial() ? finishQso() : fail(`Intercâmbio incorreto. Era 599 ${formatSerial()}.`); } }
function repeat(): void { if (operatingMode === "S_AND_P") { if (!sandpController.repeat()) setFeedback("Selecione primeiro uma estação no Bandmap."); return; } if (state === QSO_TRAINING_STATES.RECEIVING_CALLSIGN) transmitMany(stationCallsigns.length ? stationCallsigns : [stationCallsign], preferences.rxEnvironment ? preferences.stationCount : 1); else if (state === QSO_TRAINING_STATES.RECEIVING_EXCHANGE) transmit(`599 ${formatSerial()}`); else if (state === QSO_TRAINING_STATES.CALLING_CQ) transmit(`CQ CQ ${preferences.operatorCall}`); }
function macro(key: string): void { if (!running()) return; if (operatingMode === "S_AND_P") { if (key === "F6") repeat(); return; } if (key === "F1") { callCq(); return; } if (key === "F6") { repeat(); return; } const content: Record<string, string> = { F2: `599 ${formatSerial()}`, F3: "TU", F4: stationCallsign, F5: callsign.value.trim().toUpperCase() || stationCallsign, F7: "?", F8: "AGN", F9: "NR?", F10: "CALL?" }; const text = content[key]; if (!text) return; const old = state; if (key === "F4" || key === "F5") setState(QSO_TRAINING_STATES.SENDING_CALLSIGN); const duration = transmit(text); if (key === "F4" || key === "F5") schedule(() => { if (running()) setState(old); }, duration + 50); setFeedback(`Transmitindo ${text}.`); }
function sessionRecord(): SessionRecord { return { endedAt: new Date().toISOString(), seconds: elapsedSeconds(), qsos: validQsos, errors, accuracy: accuracy(), rate: rate(), bestStreak: bestSessionStreak, initialWpm, finalWpm: currentWpm() }; }
function showSummary(): void { const record = sessionRecord(); element<HTMLElement>("#summary-content").innerHTML = `<div>Tempo<strong>${String(Math.floor(record.seconds / 60)).padStart(2, "0")}:${String(record.seconds % 60).padStart(2, "0")}</strong></div><div>QSOs<strong>${record.qsos}</strong></div><div>Acertos<strong>${record.qsos}</strong></div><div>Erros<strong>${record.errors}</strong></div><div>Precisão<strong>${record.accuracy}%</strong></div><div>WPM<strong>${record.initialWpm} → ${record.finalWpm}</strong></div><div>Melhor sequência<strong>${record.bestStreak}</strong></div><div>QSO por hora<strong>${record.rate}</strong></div>`; element<HTMLElement>("#best-accuracy").textContent = `${stored.bestAccuracy}%`; element<HTMLElement>("#best-streak").textContent = String(stored.bestStreak); element<HTMLElement>("#best-rate").textContent = String(stored.bestRate); summaryDialog.showModal(); }
function endSession(show = true): void { const wasRunning = running(); sessionActive = false; callRequestId += 1; sandpController.stop(); if (operatingMode === "S_AND_P") bandmapView.render(); closeConditions(false); stopTransmission(); if (scheduledAction) window.clearTimeout(scheduledAction); if (sessionEndId) window.clearTimeout(sessionEndId); if (timerId) window.clearInterval(timerId); scheduledAction = undefined; sessionEndId = undefined; timerId = undefined; if (!wasRunning || sessionSaved) return; const record = sessionRecord(); sessionSaved = true; stored.bestAccuracy = Math.max(stored.bestAccuracy, record.accuracy); stored.bestStreak = Math.max(stored.bestStreak, record.bestStreak); stored.bestRate = Math.max(stored.bestRate, record.rate); stored.history = [record, ...stored.history].slice(0, 20); saveStorage(); setState(QSO_TRAINING_STATES.STOPPED); startButton.textContent = "INICIAR TREINO"; if (show) showSummary(); else setFeedback("Treino interrompido."); }
async function startSandPSession(requestId: number): Promise<void> { setState(QSO_TRAINING_STATES.RECEIVING_CALLSIGN); setFeedback("Carregando estações no Bandmap..."); const [selected, database] = await Promise.all([selectCallsigns(BANDMAP_40M.stationCount, [preferences.operatorCall]), loadCallsignDatabase()]); if (!running() || operatingMode !== "S_AND_P" || requestId !== callRequestId) return; callsignDatabase = database; bandmapEngine.generate(selected, { baseWpm: currentWpm(), baseToneHz: preferences.toneHz, spottedAt: Date.now() }); virtualVfo.tune(BANDMAP_40M.initialKhz); sandpController.start(); bandmapView.render(); element<HTMLElement>("#bandmap-panel").focus(); setFeedback("Selecione uma estação no Bandmap ou use Ctrl + ↑/↓."); }
async function startSession(): Promise<void> { if (!await unlockAudio() || running()) return; summaryDialog.close(); validQsos = 0; errors = 0; streak = 0; bestSessionStreak = 0; answerHistory = []; qsoCompletedAt = []; qsoSerial = 1; serial.value = "001"; wpmInput.value = String(preferences.wpm); initialWpm = preferences.wpm; sessionStartedAt = Date.now(); sessionSaved = false; sessionActive = true; timerId = window.setInterval(updateUi, 1000); sessionEndId = window.setTimeout(() => endSession(), preferences.durationMinutes * 60_000); startButton.textContent = "TREINO ATIVO"; clearQso(); audioEngine?.startEnvironment(rxEnvironmentSettings(), preferences.toneHz); updateRxStatus(); updateUi(); if (operatingMode === "S_AND_P") { const requestId = ++callRequestId; await startSandPSession(requestId); } else { setState(QSO_TRAINING_STATES.CALLING_CQ); callCq(); } }
const advancedEffectSelectors = ["#setting-signal-variation", "#setting-frequency-variation", "#setting-slow-fading", "#setting-speed-variation"] as const;
function updateAdvancedControls(): void { const enabled = element<HTMLInputElement>("#setting-rx-environment").checked; element<HTMLDivElement>("#advanced-audio-controls").classList.toggle("disabled", !enabled); element<HTMLDivElement>("#advanced-audio-controls").querySelectorAll<HTMLInputElement | HTMLSelectElement>("input, select").forEach((control) => { control.disabled = !enabled; }); advancedEffectSelectors.forEach((selector) => { element<HTMLInputElement>(selector).disabled = !enabled; }); }
function updateRxOutputs(): void { (["band-noise", "qrn", "qrm"] as const).forEach((name) => { element<HTMLOutputElement>(`#setting-${name}-value`).value = `${element<HTMLInputElement>(`#setting-${name}`).value}%`; }); }
function syncAdvancedPanel(): void { element<HTMLInputElement>("#setting-rx-environment").checked = preferences.rxEnvironment; element<HTMLSelectElement>("#setting-rx-preset").value = preferences.rxPreset; element<HTMLSelectElement>("#setting-station-count").value = String(preferences.stationCount); element<HTMLInputElement>("#setting-band-noise").value = String(Math.round(preferences.bandNoiseLevel * 100)); element<HTMLInputElement>("#setting-qrn").value = String(Math.round(preferences.qrnLevel * 100)); element<HTMLInputElement>("#setting-qrm").value = String(Math.round(preferences.qrmLevel * 100)); element<HTMLInputElement>("#setting-signal-variation").checked = preferences.signalVariation; element<HTMLInputElement>("#setting-frequency-variation").checked = preferences.frequencyVariation; element<HTMLInputElement>("#setting-slow-fading").checked = preferences.slowFading; element<HTMLInputElement>("#setting-speed-variation").checked = preferences.stationSpeedVariation; updateRxOutputs(); updateAdvancedControls(); updateRxStatus(); }
function persistAdvancedPanel(announce = true): void { preferences = { ...preferences, rxEnvironment: element<HTMLInputElement>("#setting-rx-environment").checked, rxPreset: element<HTMLSelectElement>("#setting-rx-preset").value as RxPreset, bandNoiseLevel: Number(element<HTMLInputElement>("#setting-band-noise").value) / 100, qrnLevel: Number(element<HTMLInputElement>("#setting-qrn").value) / 100, qrmLevel: Number(element<HTMLInputElement>("#setting-qrm").value) / 100, signalVariation: element<HTMLInputElement>("#setting-signal-variation").checked, frequencyVariation: element<HTMLInputElement>("#setting-frequency-variation").checked, slowFading: element<HTMLInputElement>("#setting-slow-fading").checked, stationSpeedVariation: element<HTMLInputElement>("#setting-speed-variation").checked, stationCount: clampStationCount(Number(element<HTMLSelectElement>("#setting-station-count").value)) }; stored.preferences = preferences; saveStorage(); updateRxOutputs(); updateAdvancedControls(); if (running() && preferences.rxEnvironment) audioEngine?.startEnvironment(rxEnvironmentSettings(), preferences.toneHz); else if (!preferences.rxEnvironment) audioEngine?.stopEnvironment(); updateRxStatus(); if (announce) setFeedback(preferences.rxEnvironment ? running() ? "Ambiente RX ativo. Ajustes aplicados suavemente." : "Ambiente RX pronto. Ele começará ao iniciar o treino." : "Ambiente RX desligado. O CW principal permanece disponível."); }
function applyRxPreset(): void { const preset = element<HTMLSelectElement>("#setting-rx-preset").value as RxPreset; const levels = RX_PRESETS[preset]; element<HTMLInputElement>("#setting-band-noise").value = String(levels.bandNoiseLevel * 100); element<HTMLInputElement>("#setting-qrn").value = String(levels.qrnLevel * 100); element<HTMLInputElement>("#setting-qrm").value = String(levels.qrmLevel * 100); persistAdvancedPanel(); }
function openSettings(): void { element<HTMLInputElement>("#setting-wpm").value = String(preferences.wpm); element<HTMLInputElement>("#setting-min-wpm").value = String(preferences.minWpm); element<HTMLInputElement>("#setting-max-wpm").value = String(preferences.maxWpm); element<HTMLInputElement>("#setting-tone").value = String(preferences.toneHz); const volumePercent = Math.round(preferences.volume * 100); element<HTMLInputElement>("#setting-volume").value = String(volumePercent); element<HTMLOutputElement>("#setting-volume-value").value = `${volumePercent}%`; element<HTMLInputElement>("#setting-adaptive").checked = preferences.adaptive; element<HTMLInputElement>("#setting-operator").value = preferences.operatorCall; element<HTMLSelectElement>("#setting-duration").value = String(preferences.durationMinutes); settingsDialog.showModal(); }
function saveSettings(event: SubmitEvent): void { event.preventDefault(); const min = clampWpm(Number(element<HTMLInputElement>("#setting-min-wpm").value)); const max = Math.max(min, clampWpm(Number(element<HTMLInputElement>("#setting-max-wpm").value))); preferences = { ...preferences, wpm: Math.max(min, Math.min(max, clampWpm(Number(element<HTMLInputElement>("#setting-wpm").value)))), minWpm: min, maxWpm: max, toneHz: Math.max(300, Math.min(1000, Math.round(Number(element<HTMLInputElement>("#setting-tone").value)))), volume: Math.max(0, Math.min(1, Number(element<HTMLInputElement>("#setting-volume").value) / 100)), adaptive: element<HTMLInputElement>("#setting-adaptive").checked, operatorCall: element<HTMLInputElement>("#setting-operator").value.toUpperCase().replace(/[^A-Z0-9/]/g, "") || defaults.operatorCall, durationMinutes: Number(element<HTMLSelectElement>("#setting-duration").value) as TrainingPreferences["durationMinutes"] }; stored.preferences = preferences; saveStorage(); audioEngine?.setVolume(preferences.volume); if (running()) audioEngine?.updateEnvironment(rxEnvironmentSettings(), preferences.toneHz); if (!running()) wpmInput.value = String(preferences.wpm); updateUi(); settingsDialog.close(); setFeedback(preferences.rxEnvironment ? "Configurações salvas. Ambiente RX preservado." : "Configurações salvas. Áudio limpo ativo."); }
const bind = (selector: string, action: () => void): void => element<HTMLButtonElement>(selector).addEventListener("click", action); bind("#settings-icon", openSettings); bind("#audio-test", () => { void testAudio(); }); bind("#start-button", () => { void startSession(); }); bind("#stop-button", () => endSession()); bind("#wipe-action", clearQso); bind("#conditions-toggle", toggleConditions); bind("#close-conditions", () => closeConditions()); bind("#mode-run", () => switchOperatingMode("RUN")); bind("#mode-sandp", () => switchOperatingMode("S_AND_P")); ["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10"].forEach((key) => bind(`#${key.toLowerCase()}`, () => macro(key))); bind("#f12", clearQso); bind("#close-summary", () => { summaryDialog.close(); callsign.focus(); }); bind("#new-session", () => { void startSession(); }); bind("#clear-history", () => { stored.history = []; saveStorage(); setFeedback("Histórico local apagado. Preferências e melhores marcas foram preservadas."); });
const volumeSetting = element<HTMLInputElement>("#setting-volume");
volumeSetting.addEventListener("input", () => { element<HTMLOutputElement>("#setting-volume-value").value = `${volumeSetting.value}%`; });
volumeSetting.addEventListener("change", () => { const previewVolume = Number(volumeSetting.value) / 100; const previewTone = Number(element<HTMLInputElement>("#setting-tone").value); void testAudio(previewVolume, previewTone); });
element<HTMLInputElement>("#setting-rx-environment").addEventListener("change", () => persistAdvancedPanel());
element<HTMLSelectElement>("#setting-rx-preset").addEventListener("change", applyRxPreset);
advancedEffectSelectors.forEach((selector) => element<HTMLInputElement>(selector).addEventListener("change", () => persistAdvancedPanel()));
element<HTMLSelectElement>("#setting-station-count").addEventListener("change", () => persistAdvancedPanel());
(["#setting-band-noise", "#setting-qrn", "#setting-qrm"] as const).forEach((selector) => element<HTMLInputElement>(selector).addEventListener("input", () => persistAdvancedPanel(false)));
element<HTMLFormElement>("#settings-form").addEventListener("submit", saveSettings); callsign.addEventListener("input", () => { callsign.value = callsign.value.toUpperCase().replace(/[^A-Z0-9/]/g, ""); }); [receivedRst, exchange].forEach((input) => input.addEventListener("input", () => { input.value = input.value.replace(/\D/g, ""); })); wpmInput.addEventListener("change", () => { wpmInput.value = String(Math.max(preferences.minWpm, Math.min(preferences.maxWpm, currentWpm()))); updateUi(); }); [callsign, receivedRst, exchange].forEach((input) => input.addEventListener("keydown", (event) => { if (event.key === "Enter") { event.preventDefault(); submit(); } })); document.addEventListener("keydown", (event) => { const target = event.target; const editing = target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement || target instanceof HTMLSelectElement || (target instanceof HTMLElement && target.isContentEditable); if (event.ctrlKey && !editing && operatingMode === "S_AND_P" && running() && (event.key === "ArrowDown" || event.key === "ArrowUp")) { event.preventDefault(); sandpController.navigate(event.key === "ArrowDown" ? 1 : -1); return; } const actions: Record<string, () => void> = { F1: () => macro("F1"), F2: () => macro("F2"), F3: () => macro("F3"), F4: () => macro("F4"), F5: () => macro("F5"), F6: () => macro("F6"), F7: () => macro("F7"), F8: () => macro("F8"), F9: () => macro("F9"), F10: () => macro("F10"), F12: clearQso, Escape: () => endSession() }; const action = actions[event.key]; if (action && !settingsDialog.open && !summaryDialog.open) { event.preventDefault(); action(); } }); window.addEventListener("pagehide", () => endSession(false)); window.addEventListener("beforeunload", () => stopTransmission()); wpmInput.value = String(preferences.wpm); updateOperatingModeUi(); syncAdvancedPanel(); updateUi(); callsign.focus(); void loadCallsignDatabase().then((callsigns) => { callsignDatabase = callsigns; if (callsigns.length) element<HTMLElement>("#callsign-base-status").textContent = `Base CQ WW CW 2025 — ${callsigns.length.toLocaleString("pt-BR")} estações`; });
